### ISSUE TITLE
Misleading title - there is no formContext.ui.sections

### ISSUE THREAD

**Issue by JamesHorsley** [MicrosoftDocs/powerapps-docs#3406]
The title and TOC entry seem to imply that sections on the form can be accessed via formContext.ui.sections - but there is no such collection - as the page shows in the code example you first need to access a tab and then you get the tab's sections.  While it makes sense for this to still be TOC'd as formContext.ui it really should probably be TOC'd and titled something more like "formContext.ui Tab Sections".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 006a1fa1-4229-036d-c756-78ce341ae39d
* Version Independent ID: 324740b1-606b-7481-1568-fc2c577ace30
* Content: [formContext.ui.sections (Client API reference) in model-driven apps - Power Apps](https://docs.microsoft.com/en-us/power-apps/developer/model-driven-apps/clientapi/reference/formcontext-ui-sections)
* Content Source: [powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-sections.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-sections.md)
* Service: **powerapps**
* Sub-service: **mda-developer**
* GitHub Login: @adrianorth
* Microsoft Alias: **jdaly**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @JamesHorsley. This issue has been assigned to the doc author for review.

**Comment by JimDaly** [comment]
@JamesHorsley 
Thanks for your feedback. The feature team is reviewing.

**Comment by JimDaly** [comment]
**Proposed changes:**

1. Rename/Retitle: /clientapi/reference/formContext-ui-sections.md

**Filename**: formContext-ui-sections.md => formContext-ui-tab-sections.md
**Title**: formContext.ui.sections (Client API reference) => formContext.ui Tab Sections (Client API reference)

Also change author to : HemantGaur 

2.  Rename the folder of the child topics below it:
formcontext-ui-sections => formcontext-ui-tab-sections
3. Change /model-driven-apps/TOC.yml lines 629 – 643
```
    - name: formContext.ui tab sections
      href: clientapi/reference/formcontext-ui-tab-sections.md
      items:
      - name: getLabel
        href: clientapi/reference/formcontext-ui-tab-sections/getLabel.md
      - name: getName
        href: clientapi/reference/formcontext-ui-tab-sections/getName.md
      - name: getParent
        href: clientapi/reference/formcontext-ui-tab-sections/getParent.md
      - name: getVisible
        href: clientapi/reference/formcontext-ui-tab-sections/getVisible.md
      - name: setLabel
        href: clientapi/reference/formcontext-ui-tab-sections/setLabel.md
      - name: setVisible
        href: clientapi/reference/formcontext-ui-tab-sections/setVisible.md

```
4.  Add re-directs to .openpublishing.redirection.json to account for the changes:
```

   {
      "source_path": "powerapps-docs/developer/model-driven-apps/clientapi/reference/formContext-ui-sections.md",
      "redirect_url": "/power-apps/developer/model-driven-apps/clientapi/reference/formContext-ui-tab-sections",
      "redirect_document_id": "false"
    },
    {
      "source_path": "powerapps-docs/developer/model-driven-apps/clientapi/reference/formcontext-ui-sections/getLabel.md",
      "redirect_url": "/powerapps-docs/developer/model-driven-apps/clientapi/reference/formcontext-ui-tab-sections/getLabel",
      "redirect_document_id": "false"
    },
    {
      "source_path": "powerapps-docs/developer/model-driven-apps/clientapi/reference/formcontext-ui-sections/getName.md",
      "redirect_url": "/powerapps-docs/developer/model-driven-apps/clientapi/reference/formcontext-ui-tab-sections/getName",
      "redirect_document_id": "false"
    },
    {
      "source_path": "powerapps-docs/developer/model-driven-apps/clientapi/reference/formcontext-ui-sections/getParent.md",
      "redirect_url": "/powerapps-docs/developer/model-driven-apps/clientapi/reference/formcontext-ui-tab-sections/getParent",
      "redirect_document_id": "false"
    },
    {
      "source_path": "powerapps-docs/developer/model-driven-apps/clientapi/reference/formcontext-ui-sections/getVisible.md",
      "redirect_url": "/powerapps-docs/developer/model-driven-apps/clientapi/reference/formcontext-ui-tab-sections/getVisible",
      "redirect_document_id": "false"
    },
    {
      "source_path": "powerapps-docs/developer/model-driven-apps/clientapi/reference/formcontext-ui-sections/setLabel.md",
      "redirect_url": "/powerapps-docs/developer/model-driven-apps/clientapi/reference/formcontext-ui-tab-sections/setLabel",
      "redirect_document_id": "false"
    },
    {
      "source_path": "powerapps-docs/developer/model-driven-apps/clientapi/reference/formcontext-ui-sections/setVisible.md",
      "redirect_url": "/powerapps-docs/developer/model-driven-apps/clientapi/reference/formcontext-ui-tab-sections/setVisible",
      "redirect_document_id": "false"
    }

```
