### ISSUE TITLE
pac cli paportal deployment profile example uses same adx_sitesettingid for two records

### ISSUE THREAD

**Issue by flyfishMT** [MicrosoftDocs/powerapps-docs#3496]
The .yaml example of a deployment profile uses the same adx_sitesettingid for two site settings,
adx_sitesettingid: 5ad86900-b5d7-43ac-8359-482529724979 for 
Authentication/OpenAuth/Facebook/AppId and Authentication/OpenAuth/Facebook/Secret.

I thought this should be the unique identifier of the record - Is this a copy paste error or am I not understading?  

Thank you

```yaml
adx_sitesetting:
    - adx_sitesettingid: 5ad86900-b5d7-43ac-8359-482529724979
      adx_value: ${OS.FacebookAppId} 
      adx_name: Authentication/OpenAuth/Facebook/AppId
    - adx_sitesettingid: 5ad86900-b5d7-43ac-8359-482529724979
      adx_value: contoso_sample
      adx_name: Authentication/OpenAuth/Facebook/Secret

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fffb76-5378-fe8a-62fc-0c82a6d03d6d
* Version Independent ID: 102ff357-ae01-8222-8c14-64e2a5e78a0b
* Content: [Portals support for Power Platform CLI - Power Apps](https://docs.microsoft.com/en-us/power-apps/maker/portals/power-apps-cli#use-deployment-profile)
* Content Source: [powerapps-docs/maker/portals/power-apps-cli.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/main/powerapps-docs/maker/portals/power-apps-cli.md)
* Service: **powerapps**
* Sub-service: **portals**
* GitHub Login: @neerajnandwana-msft
* Microsoft Alias: **nenandw**
